### ISSUE TITLE
urllib Redirect 308 Error

### ISSUE THREAD

**Issue by michaelkeim** [AstroJacobLi/mrf#30]
https://github.com/AstroJacobLi/mrf/blob/22e7e65c370dccd844fb7f43244bb46f6761b84a/mrf/download.py#L277-L280

In download_decals_brick, urllib throws a 308 error. Changing http://portal.nersc.gov to https://portal.nersc.gov appears to solve the issue.

**Comment by AstroJacobLi** [comment]
I changed `http` to `https` and pushed to the master branch. Hopefully it will fix the bug. On the other hand, it would be helpful if someone could update the code to accommodate DECaLS DR9. I would appreciate it if you can help :)

**Comment by michaelkeim** [comment]
Sure thing!
